import os
import json
import cohere
from typing import List, Annotated, Literal, TypedDict, Optional
from dotenv import load_dotenv
from pydantic import BaseModel
from langchain_cohere import ChatCohere
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from langgraph.graph import StateGraph, MessagesState, START, END
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
# from typing_extensions import TypedDict
from weather_api_connect import get_weather_for_timestamps
from datetime import datetime


load_dotenv()
COHERE_KEY = os.getenv("COHERE_KEY")

# Custom State
class AgentState(TypedDict):
    # messages: List[AIMessage | HumanMessage | SystemMessage]
    messages: List[str]
    topic: Optional[str]

# This function will handle the first message from the user
def first_message(state: AgentState) -> AgentState:
    message = get_last_human_message(state)
    # message = state["messages"][-1].content
    print("First message from user is: " + message)
    # We already add it to the state when in main
    # We leave it for future modifications
    # new_messages = state["messages"] + [HumanMessage(content=message)]
    # new_state = AgentState(messages=new_messages, topic=None)
    # new_state = {"messages": state["messages"] + [{"role": "user", "content": message}]}
    return state

class ClassifierResponse(BaseModel):
    topic: str

# This function will classify the user's query as either "weather"
# or "general knowledge"
def classify_query(state: AgentState) -> AgentState:
    last_message = get_last_human_message(state)
    # last_message = state["messages"][-1].content
    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )
    parser = PydanticOutputParser(
        pydantic_object=ClassifierResponse
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """ 
            Please classify the user's query into one of the following topics:
            - weather
            - general knowledge
            And answer only with topic : "weather" or "general knowledge".
            Wrap the output in this format and provide no other text:
            {format_instructions}
            """,
            ),
            ("human", "{query}"),
        ]
    # The format instructions are generated by the parser
    # and tell the LLM how to structure its output so that
    # it can be correctly parsed into the ResearchResponse object.
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser
    
    response = chain.invoke({
        "query": last_message
    })

    print("The query is classified as: " + response.topic)
    new_topic = response.topic
    new_state = AgentState(messages=state["messages"], topic=new_topic)
    return new_state

def router(state: AgentState) -> Literal["weather", "general knowledge", "unknown topic"]:
    message_topic = state["topic"]

    if message_topic == "weather":
        return "weather"
    elif message_topic == "general knowledge":
        return "general knowledge"
    else:
        return "unknown topic"

class TimeStampsResponse(BaseModel):
    timestamps: List[str]

def initial_chatbot_for_weather(state: AgentState) -> AgentState:
    print("Initial chatbot for weather called")
    last_message = get_last_human_message(state)
    # last_message = str(state["messages"][-2].content)
    print("The last message that will be timestamped is: " + last_message)
    now = datetime.now().isoformat()
    print("The current date and time is: " + now)
    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )
    parser = PydanticOutputParser(
        pydantic_object=TimeStampsResponse
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """ 
            I need you to identify from the following query, dates and times for which
            the user wants to know the weather. An example would be:
            {{
                "timestamps": ["2026-04-09T15:00:00Z", "2026-04-15T15:00:00Z"]
            }}
            The weather API will only give us the weather for the next 5 days.
            You can generate time gaps by providing subsequent hours
            Also take into consideration nows timestamp: {now}
            {format_instructions}
            """,
            ),
            ("human", "{query}"),
        ]
    # The format instructions are generated by the parser
    # and tell the LLM how to structure its output so that
    # it can be correctly parsed into the ResearchResponse object.
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser
    
    response = chain.invoke({
        "query": last_message,
        "now": now
    })
    print("Weather chatbot has responded.")
    # return {"messages": [{"role": "ai", "content": '["2026-04-09T15:00:00Z", "2026-04-15T15:00:00Z"]'}]}
    
    # print("The identified timestamps are: " + str(response.timestamps))
    # new_messages = state["messages"] + [AIMessage(content=str(response.timestamps))]
    # new_state = AgentState(messages=new_messages, topic=state["topic"])
    
    timestamps = json.dumps(response.timestamps)
    print("The identified timestamps are: " + str(timestamps))
    new_messages = state["messages"] + [AIMessage(content=timestamps)]
    new_state = AgentState(messages=new_messages, topic=state["topic"])
    
    # return {"messages": state["messages"] + [{"role": "ai", "content": str(response.timestamps)}]}
    return new_state

class GeneralKnowledgeResponse(BaseModel):
    explanation: str

def initial_chatbot_for_general_knowledge(state: AgentState) -> AgentState:
    print("Initial chatbot for general knowledge called")
    last_message = get_last_human_message(state)
    # last_message = state["messages"][-2].content
    print("The last message that will be answered is: " + str(last_message))
    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )
    parser = PydanticOutputParser(
        pydantic_object=GeneralKnowledgeResponse
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """ 
            You have to answer the user's query in a clear and concise way.
            Provide a detailed explanation of the general knowledge topic.
            {format_instructions}
            """,
            ),
            ("human", "{query}"),
        ]
    # The format instructions are generated by the parser
    # and tell the LLM how to structure its output so that
    # it can be correctly parsed into the ResearchResponse object.
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser
    
    response = chain.invoke({
        "query": last_message
    })
    print("The models explanation for the general knowledge question is: " + response.explanation)
    new_messages = state["messages"] + [AIMessage(content=response.explanation)]
    new_state = AgentState(messages=new_messages, topic=state["topic"])
    return new_state
    # return {"messages": state["messages"] + [{"role": "ai", "content": response.explanation}]}


def get_weather_from_api(state: AgentState) -> AgentState:
    last_message = get_last_ai_message(state)
    # last_message = state["messages"][-1].content
    # eval("[algo]") == [algo]
    # timestamps = eval(last_message)
    timestamps = json.loads(last_message)
    print("The timestamps are: " + str(timestamps))
    weather_data = get_weather_for_timestamps(timestamps)
    print("The weather data is: " + str(weather_data))
    new_messages = state["messages"] + [SystemMessage(content=str(weather_data))]
    new_state = AgentState(messages=new_messages, topic=state["topic"])
    return new_state
    # return {"messages": state["messages"] + [{"role": "system", "content": str(weather_data)}]}

class WeatherExplainerResponse(BaseModel):
    explanation: str

def weather_explainer_chatbot(state: AgentState) -> AgentState:
    print("Weather explainer chatbot called")
    # We need the lasts function weather data added to the messages
    last_message = get_last_system_message(state)
    # last_message = state["messages"][-1].content
    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )
    parser = PydanticOutputParser(
        pydantic_object=WeatherExplainerResponse
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """ 
            I need you to explain the weather data in a user friendly way.
            Please also make some planning recommendations
            All in spanish
            {format_instructions}
            """,
            ),
            ("human", "{query}"),
        ]
    # The format instructions are generated by the parser
    # and tell the LLM how to structure its output so that
    # it can be correctly parsed into the ResearchResponse object.
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser
    
    response = chain.invoke({
        "query": last_message
    })
    print("The models explanation for the weather is: " + response.explanation)
    new_messages = state["messages"] + [AIMessage(content=response.explanation)]
    new_state = AgentState(messages=new_messages, topic=state["topic"])
    return new_state
    # return {"messages": state["messages"] + [{"role": "ai", "content": response.explanation}]}



class ChatResponse(BaseModel):
    answer: str

def chatbot_with_context(state: AgentState) -> AgentState:
    print("Conversational chatbot called")

    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )

    parser = PydanticOutputParser(
        pydantic_object=ChatResponse
    )

    # We use all history
    messages = state["messages"]

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """
            You are a helpful assistant.
            Continue the conversation based on previous context.
            Just respond naturally.

            {format_instructions}
            """
            ),
            ("placeholder", "{messages}"),
        ]
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser

    response = chain.invoke({
        "messages": messages
    })

    new_messages = state["messages"] + [AIMessage(content=response.answer)]
    new_state = AgentState(messages=new_messages, topic=state["topic"])
    return new_state
    # return {
    #     "messages": state["messages"] + [
    #         {"role": "ai", "content": response.answer}
    #     ]
    # }

def router_entry(state: AgentState) -> Literal["new_query", "followup"]:
    # If there is any previous AI message,
    # we consider this a followup, otherwise it's a new query
    # for msg in reversed(state["messages"]):
    #     if msg.type == "ai":
    #         return "followup"
    if state["topic"] is not None:
        return "followup"
    return "new_query"

def weather_agent():
    graph = StateGraph(AgentState)
    graph.add_node("first_message", first_message)
    graph.add_node("classify_query", classify_query)
    graph.add_node("initial_chatbot_for_weather", initial_chatbot_for_weather)
    graph.add_node("initial_chatbot_for_general_knowledge", initial_chatbot_for_general_knowledge)
    graph.add_node("get_weather_from_api", get_weather_from_api)
    graph.add_node("weather_explainer_chatbot", weather_explainer_chatbot)
    graph.add_node("chatbot_with_context", chatbot_with_context)
    
    graph.add_edge(START, "first_message")
    graph.add_conditional_edges(
        "first_message",
        router_entry,
        {
            "new_query": "classify_query",
            "followup": "chatbot_with_context"
        }
    )
    graph.add_conditional_edges(
        "classify_query",
        router,
        {
            "weather": "initial_chatbot_for_weather",
            "general knowledge": "initial_chatbot_for_general_knowledge",
            "unknown topic": END
        }
    )
    graph.add_edge("initial_chatbot_for_weather", "get_weather_from_api")
    graph.add_edge("get_weather_from_api", "weather_explainer_chatbot")
    graph.add_edge("weather_explainer_chatbot", END)
    graph.add_edge("initial_chatbot_for_general_knowledge", END)
    graph = graph.compile()
    return graph
    
# def weather_agent_connect(message: str):
#     graph = weather_agent()    
#     graph.invoke({"messages": [{"role": "user", "content": message}]})
#     return

# def main():
#     message = input("Ask me something about the weather or general knowledge: ")
#     weather_agent_connect(message)
#     return

def get_last_human_message(state: AgentState) -> Optional[str]:
    for msg in reversed(state["messages"]):
        if msg.type == "human":
            return msg.content
    return None

def get_last_ai_message(state: AgentState) -> Optional[str]:
    for msg in reversed(state["messages"]):
        if msg.type == "ai":
            return msg.content
    return None

def get_last_system_message(state: AgentState) -> Optional[str]:
    for msg in reversed(state["messages"]):
        if msg.type == "system":
            return msg.content
    return None

def main():
    graph = weather_agent()
    state = AgentState(messages=[], topic=None)

    while True:
        message = input("You: ")

        if message.lower() in ["exit", "quit"]:
            print("Exiting the chatbot. Goodbye!")
            break

        if message.lower() in ["reset", "nuevo", "new"]:
            state["topic"] = None
            message = input("You (for new topic): ")

        # We add the user's message to the state
        state["messages"].append(HumanMessage(content=message))

        # We execute the graph
        state = graph.invoke(state)

        # We find the last AI response
        # last_ai = None
        # for msg in reversed(state["messages"]):
        #     if msg.type == "ai":
        #         last_ai = msg.content
        #         break

        # print("AI:", last_ai)

if __name__ == "__main__":
    main()