import os
import cohere
from typing import List, Annotated, Literal
from dotenv import load_dotenv
from pydantic import BaseModel
from langchain_cohere import ChatCohere
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from langgraph.graph import StateGraph, MessagesState, START, END
from typing_extensions import TypedDict
from weather_api_connect import get_weather_for_timestamps
from datetime import datetime
load_dotenv()
COHERE_KEY = os.getenv("COHERE_KEY")



# Custom State
# No custom state, we only need messages

# This function will handle the first message from the user
def first_message(state: MessagesState) -> MessagesState:
    message = state["messages"][-1].content
    print("First message from user is: " + message)
    # We already add it to the state when in main
    # We leave it for future modifications
    new_state = {"messages": state["messages"] + [{"role": "user", "content": message}]}
    return new_state

class ClassifierResponse(BaseModel):
    topic: str

# This function will classify the user's query as either "weather"
# or "general knowledge"
def classify_query(state: MessagesState) -> MessagesState:
    last_message = state["messages"][-1].content
    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )
    parser = PydanticOutputParser(
        pydantic_object=ClassifierResponse
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """ 
            Please classify the user's query into one of the following topics:
            - weather
            - general knowledge
            And answer only with topic : "weather" or "general knowledge".
            Wrap the output in this format and provide no other text:
            {format_instructions}
            """,
            ),
            ("human", "{query}"),
        ]
    # The format instructions are generated by the parser
    # and tell the LLM how to structure its output so that
    # it can be correctly parsed into the ResearchResponse object.
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser
    
    response = chain.invoke({
        "query": last_message
    })

    print("The query is classified as: " + response.topic)
    return {"messages": state["messages"] + [{"role": "system", "content": response.topic}]}

def router(state: MessagesState) -> Literal["weather", "general knowledge", "unknown topic"]:
    last_message = state["messages"][-1].content

    if last_message == "weather":
        return "weather"
    elif last_message == "general knowledge":
        return "general knowledge"
    else:
        return "unknown topic"

class TimeStampsResponse(BaseModel):
    timestamps: List[str]

def initial_chatbot_for_weather(state: MessagesState) -> MessagesState:
    print("Initial chatbot for weather called")
    last_message = str(state["messages"][-2].content)
    print("The last message that will be timestamped is: " + last_message)
    now = datetime.now().isoformat()
    print("The current date and time is: " + now)
    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )
    parser = PydanticOutputParser(
        pydantic_object=TimeStampsResponse
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """ 
            I need you to identify from the following query, dates and times for which
            the user wants to know the weather. An example would be:
            {{
                "timestamps": ["2026-04-09T15:00:00Z", "2026-04-15T15:00:00Z"]
            }}
            The weather API will only give us the weather for the next 5 days.
            You can generate time gaps by providing subsequent hours
            Also take into consideration nows timestamp: {now}
            {format_instructions}
            """,
            ),
            ("human", "{query}"),
        ]
    # The format instructions are generated by the parser
    # and tell the LLM how to structure its output so that
    # it can be correctly parsed into the ResearchResponse object.
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser
    
    response = chain.invoke({
        "query": last_message,
        "now": now
    })
    print("Weather chatbot has responded.")
    # return {"messages": [{"role": "ai", "content": '["2026-04-09T15:00:00Z", "2026-04-15T15:00:00Z"]'}]}
    print("The identified timestamps are: " + str(response.timestamps))
    return {"messages": state["messages"] + [{"role": "ai", "content": str(response.timestamps)}]}

class GeneralKnowledgeResponse(BaseModel):
    explanation: str

def initial_chatbot_for_general_knowledge(state: MessagesState) -> MessagesState:
    print("Initial chatbot for general knowledge called")
    last_message = state["messages"][-2].content
    print("The last message that will be answered is: " + str(last_message))
    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )
    parser = PydanticOutputParser(
        pydantic_object=GeneralKnowledgeResponse
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """ 
            You have to answer the user's query in a clear and concise way.
            Provide a detailed explanation of the general knowledge topic.
            {format_instructions}
            """,
            ),
            ("human", "{query}"),
        ]
    # The format instructions are generated by the parser
    # and tell the LLM how to structure its output so that
    # it can be correctly parsed into the ResearchResponse object.
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser
    
    response = chain.invoke({
        "query": last_message
    })
    print("The models explanation for the general knowledge question is: " + response.explanation)
    return {"messages": state["messages"] + [{"role": "ai", "content": response.explanation}]}


def get_weather_from_api(state: MessagesState) -> MessagesState:
    last_message = state["messages"][-1].content
    # eval("[algo]") == [algo]
    timestamps = eval(last_message)
    print("The timestamps are: " + str(timestamps))
    weather_data = get_weather_for_timestamps(timestamps)
    print("The weather data is: " + str(weather_data))
    return {"messages": state["messages"] + [{"role": "system", "content": str(weather_data)}]}

class WeatherExplainerResponse(BaseModel):
    explanation: str

def weather_explainer_chatbot(state: MessagesState) -> MessagesState:
    print("Weather explainer chatbot called")
    # We need the lasts function weather data added to the messages
    last_message = state["messages"][-1].content
    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )
    parser = PydanticOutputParser(
        pydantic_object=WeatherExplainerResponse
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """ 
            I need you to explain the weather data in a user friendly way.
            Please also make some planning recommendations
            {format_instructions}
            """,
            ),
            ("human", "{query}"),
        ]
    # The format instructions are generated by the parser
    # and tell the LLM how to structure its output so that
    # it can be correctly parsed into the ResearchResponse object.
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser
    
    response = chain.invoke({
        "query": last_message
    })
    print("The models explanation for the weather is: " + response.explanation)
    return {"messages": state["messages"] + [{"role": "ai", "content": response.explanation}]}



class ChatResponse(BaseModel):
    answer: str

def chatbot_with_context(state: MessagesState) -> MessagesState:
    print("Conversational chatbot called")

    llm = ChatCohere(
        cohere_api_key=COHERE_KEY,
        model="command-a-03-2025"
    )

    parser = PydanticOutputParser(
        pydantic_object=ChatResponse
    )

    # We use all history
    messages = state["messages"]

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",
            """
            You are a helpful assistant.
            Continue the conversation based on previous context.
            Just respond naturally.

            {format_instructions}
            """
            ),
            ("placeholder", "{messages}"),
        ]
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser

    response = chain.invoke({
        "messages": messages
    })

    return {
        "messages": state["messages"] + [
            {"role": "ai", "content": response.answer}
        ]
    }

def router_entry(state: MessagesState) -> Literal["new_query", "followup"]:
    # If there is any previous AI message,
    # we consider this a followup, otherwise it's a new query
    for msg in reversed(state["messages"]):
        if msg.type == "ai":
            return "followup"

    return "new_query"

def weather_agent():
    graph = StateGraph(MessagesState)
    graph.add_node("first_message", first_message)
    graph.add_node("classify_query", classify_query)
    graph.add_node("initial_chatbot_for_weather", initial_chatbot_for_weather)
    graph.add_node("initial_chatbot_for_general_knowledge", initial_chatbot_for_general_knowledge)
    graph.add_node("get_weather_from_api", get_weather_from_api)
    graph.add_node("weather_explainer_chatbot", weather_explainer_chatbot)
    graph.add_node("chatbot_with_context", chatbot_with_context)
    
    graph.add_edge(START, "first_message")
    graph.add_conditional_edges(
        "first_message",
        router_entry,
        {
            "new_query": "classify_query",
            "followup": "chatbot_with_context"
        }
    )
    graph.add_conditional_edges(
        "classify_query",
        router,
        {
            "weather": "initial_chatbot_for_weather",
            "general knowledge": "initial_chatbot_for_general_knowledge",
            "unknown topic": END
        }
    )
    graph.add_edge("initial_chatbot_for_weather", "get_weather_from_api")
    graph.add_edge("get_weather_from_api", "weather_explainer_chatbot")
    graph.add_edge("weather_explainer_chatbot", END)
    graph.add_edge("initial_chatbot_for_general_knowledge", END)
    graph = graph.compile()
    return graph
    
# def weather_agent_connect(message: str):
#     graph = weather_agent()    
#     graph.invoke({"messages": [{"role": "user", "content": message}]})
#     return

# def main():
#     message = input("Ask me something about the weather or general knowledge: ")
#     weather_agent_connect(message)
#     return

def main():
    graph = weather_agent()
    state = {"messages": []}

    while True:
        message = input("You: ")

        # We add the user's message to the state
        state["messages"].append({"role": "user", "content": message})

        # We execute the graph
        state = graph.invoke(state)

        # We find the last AI response
        last_ai = None
        for msg in reversed(state["messages"]):
            if msg.type == "ai":
                last_ai = msg.content
                break

        print("AI:", last_ai)

if __name__ == "__main__":
    main()